addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.4")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.10.0")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"  % "2.3.0")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.13.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.9.2")
