addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.10.0")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"  % "2.0.9")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.11.1")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.12")
